version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=10s
      - SERVER_WRITE_TIMEOUT=10s
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=auth
      - DB_SSLMODE=disable
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24h
      - API_KEY_HEADER=X-API-Key
    volumes:
      - ./web:/app/web
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
